/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.objective.worldcup.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Group service. Represents a row in the &quot;WorldCup_Group&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.objective.worldcup.model.impl.GroupModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.objective.worldcup.model.impl.GroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Group
 * @see com.objective.worldcup.model.impl.GroupImpl
 * @see com.objective.worldcup.model.impl.GroupModelImpl
 * @generated
 */
@ProviderType
public interface GroupModel extends BaseModel<Group>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a group model instance should use the {@link Group} interface instead.
	 */

	/**
	 * Returns the primary key of this group.
	 *
	 * @return the primary key of this group
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this group.
	 *
	 * @param primaryKey the primary key of this group
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this group.
	 *
	 * @return the uuid of this group
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this group.
	 *
	 * @param uuid the uuid of this group
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the grp ID of this group.
	 *
	 * @return the grp ID of this group
	 */
	public long getGrpId();

	/**
	 * Sets the grp ID of this group.
	 *
	 * @param grpId the grp ID of this group
	 */
	public void setGrpId(long grpId);

	/**
	 * Returns the group ID of this group.
	 *
	 * @return the group ID of this group
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this group.
	 *
	 * @param groupId the group ID of this group
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this group.
	 *
	 * @return the company ID of this group
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this group.
	 *
	 * @param companyId the company ID of this group
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this group.
	 *
	 * @return the user ID of this group
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this group.
	 *
	 * @param userId the user ID of this group
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this group.
	 *
	 * @return the user uuid of this group
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this group.
	 *
	 * @param userUuid the user uuid of this group
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this group.
	 *
	 * @return the user name of this group
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this group.
	 *
	 * @param userName the user name of this group
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this group.
	 *
	 * @return the create date of this group
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this group.
	 *
	 * @param createDate the create date of this group
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this group.
	 *
	 * @return the modified date of this group
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this group.
	 *
	 * @param modifiedDate the modified date of this group
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this group.
	 *
	 * @return the name of this group
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this group.
	 *
	 * @param name the name of this group
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Group group);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Group> toCacheModel();

	@Override
	public Group toEscapedModel();

	@Override
	public Group toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}